package remediation

import (
	"fmt"
	"strings"

	"github.com/gamesapeca/gha-oidc-auditor/pkg/parser"
)

// GenerateAWSTerraformHCL synthesizes production-ready Terraform/OpenTofu HCL resources for AWS IAM OIDC roles.
// Generates both data "aws_iam_policy_document" with 2026 immutable sub-claims and resource "aws_iam_role".
func GenerateAWSTerraformHCL(accountID, owner, repo string, wf *parser.Workflow, job *parser.Job) string {
	if accountID == "" {
		accountID = "${var.account_id}"
	}
	if owner == "" {
		owner = "${var.github_org}"
	}
	if repo == "" {
		repo = "${var.github_repo}"
	}

	subClaim := SynthesizeSubClaim(owner, repo, wf, job)
	immutableSubClaim := SynthesizeImmutableSubClaimPattern(owner, repo, wf, job)

	cleanRepo := strings.ReplaceAll(repo, "-", "_")
	cleanRepo = strings.ReplaceAll(cleanRepo, "/", "_")
	cleanRepo = strings.ReplaceAll(cleanRepo, "${var.", "")
	cleanRepo = strings.ReplaceAll(cleanRepo, "}", "")
	if cleanRepo == "" {
		cleanRepo = "gha"
	}

	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("# Generated by gha-oidc-auditor (Least-Privilege Remediation for %s/%s)\n", owner, repo))
	sb.WriteString(fmt.Sprintf("data \"aws_iam_policy_document\" \"%s_gha_oidc_assume_role\" {\n", cleanRepo))
	sb.WriteString("  statement {\n")
	sb.WriteString("    effect  = \"Allow\"\n")
	sb.WriteString("    actions = [\"sts:AssumeRoleWithWebIdentity\"]\n\n")
	sb.WriteString("    principals {\n")
	sb.WriteString("      type        = \"Federated\"\n")
	sb.WriteString(fmt.Sprintf("      identifiers = [\"arn:aws:iam::%s:oidc-provider/token.actions.githubusercontent.com\"]\n", accountID))
	sb.WriteString("    }\n\n")
	sb.WriteString("    condition {\n")
	sb.WriteString("      test     = \"StringEquals\"\n")
	sb.WriteString("      variable = \"token.actions.githubusercontent.com:aud\"\n")
	sb.WriteString("      values   = [\"sts.amazonaws.com\"]\n")
	sb.WriteString("    }\n\n")
	sb.WriteString("    condition {\n")
	sb.WriteString("      test     = \"StringLike\"\n")
	sb.WriteString("      variable = \"token.actions.githubusercontent.com:sub\"\n")
	sb.WriteString("      values = [\n")
	sb.WriteString(fmt.Sprintf("        \"%s\",\n", subClaim))
	sb.WriteString(fmt.Sprintf("        \"%s\" # July 2026 Immutable Format\n", immutableSubClaim))
	sb.WriteString("      ]\n")
	sb.WriteString("    }\n")
	sb.WriteString("  }\n")
	sb.WriteString("}\n\n")

	sb.WriteString(fmt.Sprintf("resource \"aws_iam_role\" \"%s_gha_deploy_role\" {\n", cleanRepo))
	sb.WriteString(fmt.Sprintf("  name               = \"%s-gha-deploy\"\n", cleanRepo))
	sb.WriteString(fmt.Sprintf("  assume_role_policy = data.aws_iam_policy_document.%s_gha_oidc_assume_role.json\n", cleanRepo))
	sb.WriteString("  tags = {\n")
	sb.WriteString("    ManagedBy = \"gha-oidc-auditor\"\n")
	sb.WriteString("    Security  = \"Least-Privilege-OIDC\"\n")
	sb.WriteString("  }\n")
	sb.WriteString("}\n")

	return sb.String()
}

// GenerateGCPTerraformHCL synthesizes production-ready Terraform HCL for GCP Workload Identity Federation provider.
func GenerateGCPTerraformHCL(poolID, owner, repo string, wf *parser.Workflow, job *parser.Job) string {
	if poolID == "" {
		poolID = "${var.wif_pool_id}"
	}
	if owner == "" {
		owner = "${var.github_org}"
	}
	if repo == "" {
		repo = "${var.github_repo}"
	}

	cleanRepo := strings.ReplaceAll(repo, "-", "_")
	cleanRepo = strings.ReplaceAll(cleanRepo, "/", "_")
	cleanRepo = strings.ReplaceAll(cleanRepo, "${var.", "")
	cleanRepo = strings.ReplaceAll(cleanRepo, "}", "")
	if cleanRepo == "" {
		cleanRepo = "gha"
	}

	envName := ""
	if job != nil {
		envName = job.GetEnvironmentName()
	}

	var condition string
	if envName != "" {
		condition = fmt.Sprintf("assertion.repository == '%s/%s' && assertion.environment == '%s'", owner, repo, envName)
	} else {
		condition = fmt.Sprintf("assertion.repository == '%s/%s' && assertion.ref == 'refs/heads/main'", owner, repo)
	}

	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("# Generated by gha-oidc-auditor (GCP WIF Remediation for %s/%s)\n", owner, repo))
	sb.WriteString(fmt.Sprintf("resource \"google_iam_workload_identity_pool_provider\" \"%s_gha_provider\" {\n", cleanRepo))
	sb.WriteString(fmt.Sprintf("  workload_identity_pool_id          = %s\n", poolID))
	sb.WriteString(fmt.Sprintf("  workload_identity_pool_provider_id = \"%s-gha-provider\"\n", cleanRepo))
	sb.WriteString(fmt.Sprintf("  display_name                       = \"GitHub Actions Provider for %s\"\n\n", cleanRepo))
	sb.WriteString("  attribute_mapping = {\n")
	sb.WriteString("    \"google.subject\"             = \"assertion.sub\"\n")
	sb.WriteString("    \"attribute.actor\"            = \"assertion.actor\"\n")
	sb.WriteString("    \"attribute.repository\"       = \"assertion.repository\"\n")
	sb.WriteString("    \"attribute.repository_id\"    = \"assertion.repository_id\"\n")
	sb.WriteString("    \"attribute.repository_owner\" = \"assertion.repository_owner\"\n")
	sb.WriteString("  }\n\n")
	sb.WriteString(fmt.Sprintf("  attribute_condition = \"%s\"\n\n", condition))
	sb.WriteString("  oidc {\n")
	sb.WriteString("    issuer_uri = \"https://token.actions.githubusercontent.com\"\n")
	sb.WriteString("  }\n")
	sb.WriteString("}\n")

	return sb.String()
}

// GenerateAzureTerraformHCL synthesizes production-ready Terraform HCL for Azure Entra ID federated credentials.
func GenerateAzureTerraformHCL(appObjectID, owner, repo string, wf *parser.Workflow, job *parser.Job) string {
	if appObjectID == "" {
		appObjectID = "${azuread_application.gha_app.object_id}"
	}
	if owner == "" {
		owner = "${var.github_org}"
	}
	if repo == "" {
		repo = "${var.github_repo}"
	}

	cleanRepo := strings.ReplaceAll(repo, "-", "_")
	cleanRepo = strings.ReplaceAll(cleanRepo, "/", "_")
	cleanRepo = strings.ReplaceAll(cleanRepo, "${var.", "")
	cleanRepo = strings.ReplaceAll(cleanRepo, "}", "")
	if cleanRepo == "" {
		cleanRepo = "gha"
	}

	subClaim := SynthesizeSubClaim(owner, repo, wf, job)

	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("# Generated by gha-oidc-auditor (Azure Federated Credential Remediation for %s/%s)\n", owner, repo))
	sb.WriteString(fmt.Sprintf("resource \"azuread_application_federated_identity_credential\" \"%s_gha_fed_cred\" {\n", cleanRepo))
	sb.WriteString(fmt.Sprintf("  application_object_id = %s\n", appObjectID))
	sb.WriteString(fmt.Sprintf("  display_name          = \"%s-gha-federated-credential\"\n", cleanRepo))
	sb.WriteString(fmt.Sprintf("  description           = \"GitHub Actions OIDC federation for %s/%s\"\n", owner, repo))
	sb.WriteString("  audiences             = [\"api://AzureADTokenExchange\"]\n")
	sb.WriteString("  issuer                = \"https://token.actions.githubusercontent.com\"\n")
	sb.WriteString(fmt.Sprintf("  subject               = \"%s\"\n", subClaim))
	sb.WriteString("}\n")

	return sb.String()
}

